
if true then return end -- Remove this line and complete settings below

manualDns = {
   acceptTerms = true,
   email = "operator@example.com",
   domains = {"device.example.com"},
   production = false
}
