{
 "title": "Weather Data",
 "description": "This Grafana visualization example is designed for the tutorial:\nhttps://realtimelogic.com/articles/ESP32-and-MySQL-Cloud-Integration-Visualizing-Weather-Data",
 "tags": [
  "Xedge32",
  "ESP32",
  "MySQL"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "defaultdb",
     "rawSql": "SELECT temperature FROM defaultdb.weatherdata ORDER BY timestamp DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 0 },
   "targets": [
    {
     "dataset": "defaultdb",
     "rawSql": "SELECT temperature, timestamp FROM defaultdb.weatherdata WHERE timestamp BETWEEN $__timeFrom() AND $__timeTo()"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "defaultdb",
     "rawSql": "SELECT humidity FROM defaultdb.weatherdata ORDER BY timestamp DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 8 },
   "targets": [
    {
     "dataset": "defaultdb",
     "rawSql": "SELECT humidity, timestamp FROM defaultdb.weatherdata WHERE timestamp BETWEEN $__timeFrom() AND $__timeTo()"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "defaultdb",
     "rawSql": "SELECT pressure FROM defaultdb.weatherdata ORDER BY timestamp DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 16 },
   "targets": [
    {
     "dataset": "defaultdb",
     "sql": {
      "columns": [],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     },
     "table": "weatherdata"
    },
    {
     "dataset": "defaultdb",
     "rawSql": "SELECT pressure, timestamp FROM defaultdb.weatherdata WHERE timestamp BETWEEN $__timeFrom() AND $__timeTo()"
    }
   ]
  }
 ]
}